name: localwpx
recipe: wordpress
config:
  webroot: .wordpress
services:
  node:
    type: node:18
    build_as_root:
      - corepack enable
      - corepack prepare pnpm@latest --activate
    build:
      - pnpm install
  appserver:
    build:
      - find . -maxdepth 3 -type f -name composer.json -execdir composer install --no-interaction \;
tooling:
  pnpm:
    service: node
  pnpx:
    service: node
exclude:
  - .pnpm-store